source/mycantina.UI/ViewModels/ConsumerBottle/ConsumerBottleCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace mycantina.UI.ViewModels.ConsumerBottle
{
    public class ConsumerBottleCreateViewModel
    {
        [ScaffoldColumn(false)]
        public int ConsumerId { get; set; }
        [ScaffoldColumn(false)]
        public int BottleId { get; set; }
        [Required]
        [Display(Name = "Format")]
        public int WineFormatId { get; set; }
        public SelectList WineFormats { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateAcquired { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateOpened { get; set; }
        [Display(Name = "Quantity")]
        public int QtyOwned { get; set; }
        [Required]
        [Display(Name = "Is it in your collection?")]
        public Boolean Owned { get; set; }
        [Display(Name = "Price Paid")]
        public decimal PricePaid { get; set; }
    }
}

source/mycantina.UI/ViewModels/ConsumerBottle/ConsumerBottleDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace mycantina.UI.ViewModels.ConsumerBottle
{
    public class ConsumerBottleDetailsViewModel
    {
        public int Id { get; set; }
        [ScaffoldColumn(false)]
        public int ConsumerId { get; set; }
        [ScaffoldColumn(false)]
        public int BottleId { get; set; }
        [Display(Name = "Format")]
        public string WineFormat { get; set; }
        [DisplayFormat(DataFormatString = "{0:D}")]
        public DateTime? DateAcquired { get; set; }
        [DisplayFormat(DataFormatString = "{0:D}")]
        public DateTime? DateOpened { get; set; }
        [Display(Name = "Quantity")]
        public int QtyOwned { get; set; }
        [Display(Name = "In your collection")]
        public Boolean Owned { get; set; }
        [Display(Name = "Price Paid")]
        public decimal PricePaid { get; set; }
    }
}

source/mycantina.UI/ViewModels/ConsumerBottle/ConsumerBottleEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace mycantina.UI.ViewModels.ConsumerBottle
{
    public class ConsumerBottleEditViewModel
    {
        public int Id { get; set; }
        [ScaffoldColumn(false)]
        public int ConsumerId { get; set; }
        [Required]
        [Display(Name = "Format")]
        public int WineFormatId { get; set; }
        public SelectList WineFormats { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateAcquired { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateOpened { get; set; }
        [Display(Name = "Quantity")]
        public int QtyOwned { get; set; }
        [Required]
        [Display(Name = "Is it in your collection?")]
        public Boolean Owned { get; set; }
        [Display(Name = "Price Paid")]
        public decimal PricePaid { get; set; }
    }
}

source/mycantina.UI/ViewModels/ConsumerBottle/ConsumerBottleIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace mycantina.UI.ViewModels.ConsumerBottle
{
    public class ConsumerBottleIndexViewModel
    {
        public int Id { get; set; }
        [ScaffoldColumn(false)]
        public int ConsumerId { get; set; }
        [Display(Name = "Bottle Name")]
        public string WineName { get; set; }
        [Display(Name = "Format")]
        public string WineFormat { get; set; }
        [Display(Name = "Quantity")]
        public int QtyOwned { get; set; }
        [Display(Name = "In your collection")]
        public Boolean Owned { get; set; }
        [Display(Name = "Price Paid")]
        public decimal PricePaid { get; set; }
    }
}

source/mycantina.UI/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using mycantina.DataAccess.Models;
using mycantina.Services;
using System.Net;
using mycantina.UI.ViewModels.Review;
using SharpRepository.EfRepository;

namespace mycantina.UI.Controllers
{
    public class ReviewController : Controller
    {
        private MyCantinaDbContext _context;
        private ReviewApplicationService _reviewApplicationService;
        private EfRepository<Review> _reviewRepository;
        private EfRepository<Consumer> _consumerRepository;
        private EfRepository<Bottle> _bottleRepository;

        public ReviewController()
        {
            _context = new MyCantinaDbContext();
            _reviewRepository = new EfRepository<Review>(_context);
            _consumerRepository = new EfRepository<Consumer>(_context);
            _bottleRepository = new EfRepository<Bottle>(_context);
            _reviewApplicationService = new ReviewApplicationService(_reviewRepository,_consumerRepository,_bottleRepository);
        }

        // GET: Review / Index
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var reviews = _reviewRepository.AsQueryable().Where(r => r.ConsumerId == id);
            
            var model = reviews.Select(r => new ReviewIndexViewModel()
            {
                ConsumerId = id.Value,
                BottleId = r.BottleId,
                BottleName = r.Bottle.Name,
                Text = r.Text,
                Rating = r.Rating,
                DatePosted = r.DatePosted
            }).ToList();

            return View(model);
        }

        // GET: Review / Create
        public ActionResult Create(int? consumerId, int? bottleId)
        {
            if (consumerId == null || bottleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var consumer = _consumerRepository.Get(consumerId.Value);
            var bottle = _bottleRepository.Get(bottleId.Value);

            if (consumer == null || bottle == null)
            {
                return HttpNotFound();
            }

            var model = new ReviewCreateViewModel()
            {
                ConsumerId = consumerId.Value,
                BottleId = bottleId.Value
            };

            model.Ratings = new SelectList(new List<int>{ 1, 2, 3, 4, 5 });

            return View(model);
        }

        // POST: Review / Create
        [HttpPost]
        public ActionResult Create(ReviewCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _reviewApplicationService.AddReview(model.ConsumerId, model.BottleId, model.Text, model.Rating);
                    return RedirectToAction("Details", new { consumerId = model.ConsumerId, bottleId = model.BottleId });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex);
                }
            }

            model.Ratings = new SelectList(new List<int> { 1, 2, 3, 4, 5 });

            return View(model);
        }

        // GET: Review / Edit
        public ActionResult Edit(int? consumerId, int? bottleId)
        {
            if (consumerId == null || bottleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var consumer = _consumerRepository.Get(consumerId.Value);
            var bottle = _bottleRepository.Get(bottleId.Value);
            var review = _reviewRepository.Find(r => r.ConsumerId == consumerId.Value && r.BottleId == bottleId.Value);

            if (consumer == null || bottle == null || review == null)
            {
                return HttpNotFound();
            }
            
            var model = new ReviewEditViewModel()
            {
                ConsumerId = consumerId.Value,
                BottleId = bottleId.Value,
                Rating = review.Rating,
                Text = review.Text
            };

            model.Ratings = new SelectList(new List<int> { 1, 2, 3, 4, 5 });

            return View(model);
        }

        // POST: Review / Edit
        [HttpPost]
        public ActionResult Edit(ReviewEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _reviewApplicationService.UpdateReview(model.ConsumerId, model.BottleId, model.Text, model.Rating);
                    return RedirectToAction("Details", new { consumerId = model.ConsumerId, bottleId = model.BottleId });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex);
                }
            }

            model.Ratings = new SelectList(new int[] { 1, 2, 3, 4, 5 });

            return View(model);
        }

        // GET: Review / Details
        public ActionResult Details(int? consumerId, int? bottleId)
        {
            if (consumerId == null || bottleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var consumer = _consumerRepository.Get(consumerId.Value);
            var bottle = _bottleRepository.Get(bottleId.Value);
            var review = _reviewRepository.Find(r => r.ConsumerId == consumerId.Value && r.BottleId == bottleId.Value);

            if (consumer == null || bottle == null || review == null)
            {
                return HttpNotFound();
            }

            var model = new ReviewDetailsViewModel()
            {
                ConsumerId = consumerId.Value,
                BottleId = bottleId.Value,
                BottleName = bottle.Name,
                //Country = bottle.Country.Name,
                Region = bottle.Region.Name,
                WineType = bottle.WineType.Name,
                Year = bottle.Year,
                Producer = bottle.Producer,
                AvgPrice = (bottle.MinPrice + bottle.MaxPrice) / 2, // TODO: Fix this stuff
                Description = bottle.Description,
                Text = review.Text,
                Rating = review.Rating,
                DatePosted = review.DatePosted,
                DateModified = review.DateModified
            };

            return View(model);
        }

        // GET: Review / Delete
        public ActionResult Delete(int? consumerId, int? bottleId)
        {
            if (consumerId == null || bottleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var consumer = _consumerRepository.Get(consumerId.Value);
            var bottle = _bottleRepository.Get(bottleId.Value);
            var review = _reviewRepository.Find(r => r.ConsumerId == consumerId.Value && r.BottleId == bottleId.Value);

            if (consumer == null || bottle == null || review == null)
            {
                return HttpNotFound();
            }

            var model = new ReviewDetailsViewModel()
            {
                ConsumerId = consumerId.Value,
                BottleId = bottleId.Value,
                BottleName = review.Bottle.Name,
                Text = review.Text,
                Rating = review.Rating,
                DatePosted = review.DatePosted
            };

            return View(model);
        }

        // POST: Review / Delete
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? consumerId, int? bottleId)
        {
            if (consumerId == null || bottleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _reviewApplicationService.RemoveReview(consumerId.Value, bottleId.Value);
                    return RedirectToAction("Index", new { id = consumerId });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex);
                }
            }

            var consumer = _consumerRepository.Get(consumerId.Value);
            var bottle = _bottleRepository.Get(bottleId.Value);
            var review = _reviewRepository.Find(r => r.ConsumerId == consumerId.Value && r.BottleId == bottleId.Value);

            if (consumer == null || bottle == null || review == null)
            {
                return HttpNotFound();
            }

            var model = new ReviewDetailsViewModel()
            {
                ConsumerId = consumerId.Value,
                BottleId = bottleId.Value,
                BottleName = review.Bottle.Name,
                Text = review.Text,
                Rating = review.Rating,
                DatePosted = review.DatePosted
            };

            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
                _context = null;
            }
            base.Dispose(disposing);
        }
    }
}

source/mycantina.UI/Views/ConsumerBottle/Create.cshtml
@model mycantina.UI.ViewModels.ConsumerBottle.ConsumerBottleCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ConsumerBottleCreateViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.WineFormatId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WineFormatId", Model.WineFormats , new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WineFormatId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateAcquired, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAcquired, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAcquired, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOpened, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QtyOwned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyOwned, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtyOwned, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Owned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Owned)
                    @Html.ValidationMessageFor(model => model.Owned, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Create" class="col-md-offset-2 btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.ConsumerId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/mycantina.UI/Views/ConsumerBottle/Delete.cshtml
@model mycantina.UI.ViewModels.ConsumerBottle.ConsumerBottleDetailsViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConsumerBottleDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WineFormat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WineFormat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAcquired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAcquired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOpened)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtyOwned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtyOwned)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owned)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePaid)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.ConsumerId })
        </div>
    }
</div>

source/mycantina.UI/Views/ConsumerBottle/Details.cshtml
@model mycantina.UI.ViewModels.ConsumerBottle.ConsumerBottleDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ConsumerBottleDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WineFormat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WineFormat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAcquired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAcquired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOpened)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtyOwned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtyOwned)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owned)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePaid)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Add a review", "Create", "Review", new { consumerId = Model.ConsumerId, bottleId = Model.BottleId }, null) |
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", new { id = Model.ConsumerId })
</p>

source/mycantina.UI/Views/ConsumerBottle/Edit.cshtml
@model mycantina.UI.ViewModels.ConsumerBottle.ConsumerBottleEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ConsumerBottleEditViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.WineFormatId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WineFormatId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WineFormatId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateAcquired, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAcquired, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAcquired, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOpened, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QtyOwned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyOwned, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtyOwned, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Owned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Owned)
                    @Html.ValidationMessageFor(model => model.Owned, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.ConsumerId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/mycantina.UI/Views/ConsumerBottle/Index.cshtml
@model IEnumerable<mycantina.UI.ViewModels.ConsumerBottle.ConsumerBottleIndexViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.WineName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WineFormat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QtyOwned)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Owned)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PricePaid)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.WineName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WineFormat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QtyOwned)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Owned)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PricePaid)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>